---
fullname: Autosubst
shortname: autosubst
organization: coq-community
community: true
action: true
doi: 10.1007/978-3-319-22102-1_24

synopsis: >-
  Coq library for parallel de Bruijn substitutions

description: |-
  Autosubst is a library for the Coq proof assistant which
  provides automation for formalizing syntactic theories with
  variable binders. Given an inductive definition of syntactic
  objects in de Bruijn representation augmented with binding
  annotations, Autosubst synthesizes the parallel substitution
  operation and automatically proves the basic lemmas about
  substitutions.

publications:
- pub_url: https://www.ps.uni-saarland.de/Publications/documents/SchaeferEtAl_2015_Autosubst_-Reasoning.pdf
  pub_title: 'Autosubst: Reasoning with de Bruijn Terms and Parallel Substitutions'
  pub_doi: 10.1007/978-3-319-22102-1_24

authors:
- name: Steven Schäfer
  initial: true
- name: Tobias Tebbi
  initial: true

maintainers:
- name: Ralf Jung
  nickname: RalfJung
- name: Dan Frumin
  nickname: co-dan

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.14~") | (= "dev")}'

tested_coq_nix_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master

tested_coq_opam_versions:
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.11.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.10.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.9.0-coq-8.10'
  repo: 'mathcomp/mathcomp'

namespace: Autosubst

keywords:
- name: abstract syntax
- name: binders
- name: de Bruijn indices
- name: substitution

categories:
- name: Computer Science/Lambda Calculi
---
